server:
  port: 5000 # ElasticBeanstalk expects for Java apps to be deployed on port 5000

spring:
  application:
    name: Asteria-Alpha
  datasource:
    platform: postgres
    url: ${asteria_db}
    username: ${asteria_username}
    password: ${asteria_password}
    driver-ClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.mail.yahoo.com
    port: 587
    properties.mail.smtp.starttls.enable: true
    username: ${email_username}
    password: ${email_password}
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.auth: true
    properties.mail.smtp.connectiontimeout: 5000
    properties.mail.smtp.writetimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"
